# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RoutePlanner
                                 A QGIS plugin
 RoutePlanner
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-11-25
        copyright            : (C) 2024 by Golden Gecko
        email                : routeplanner@holisz.pl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RoutePlanner class from file RoutePlanner.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .route_planner import RoutePlanner
    return RoutePlanner(iface)
